package api

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/danielgtaylor/huma/v2"

	"github.com/prokopto-dev/nparse-plugin-regserve/internal/auth"
	"github.com/prokopto-dev/nparse-plugin-regserve/internal/core"
	"github.com/prokopto-dev/nparse-plugin-regserve/internal/identity"
	"github.com/prokopto-dev/nparse-plugin-regserve/internal/ownership"
	"github.com/prokopto-dev/nparse-plugin-regserve/internal/registry"
	"github.com/prokopto-dev/nparse-plugin-regserve/internal/release"
	"github.com/prokopto-dev/nparse-plugin-regserve/internal/review"
)

// Spec returns the OpenAPI document for every operation this service exposes.
//
// It is built by running the same registration code the server runs, so the document cannot
// describe a route that is not served or miss one that is. That is what "coverage derived from the
// route registry" means in AGENTS.md law 6: the permission gate walks this document, so a new
// operation appears in it the moment it is registered, declaration or not.
func Spec() *huma.OpenAPI {
	mux := http.NewServeMux()
	api := newHumaAPI(mux)

	// The stubs below stand in for the real dependencies. A document that described a different
	// set of operations depending on whether the instance generating it happened to have a
	// database attached would be useless as a published contract — the API is what this build
	// exposes, not what one deployment is currently able to answer.
	registerHealth(api, unavailable{})
	registerIndex(api, unavailable{})
	registerDirectory(api, DirectoryDeps{Listings: unavailable{}, Providers: identity.NewRegistry()})
	registerAuth(api, unavailable{}, unavailable{}, identity.NewRegistry())
	// No public URL: the document is generated by a build, not by a deployment, and an absolute
	// URL baked into it would be one instance's hostname published as everybody's. Claimable,
	// because this document describes what the BUILD exposes and the build exposes both doors
	// onto claiming — see the registrations below.
	registerReleases(api, unavailablePublisher{}, claimAdvice(true, true, ""))
	registerPlugins(api, unavailableOwnership{})
	registerReview(api, unavailableQueue{})
	registerTrust(api, unavailableTrust{})
	registerWeb(api, WebDeps{
		Sessions:  unavailable{},
		Tokens:    unavailableTokens{},
		Ownership: unavailableOwnership{},
		Providers: identity.NewRegistry(),
		// The claim form is part of what this build exposes, so it is in the document. The same
		// stub serves both doors, because it is the same act.
		Claimer: unavailableOwnership{},
		// The review pages are part of what this build exposes, so they are in the document
		// whether or not a given deployment has a queue wired. A spec that varied with one
		// instance's configuration would be useless as a published contract — and PERM001 walks
		// this document, so an operation missing from it is an operation no gate checks.
		Queue:     unavailableQueue{},
		Reviewers: unavailableReviewers{},
		// The moderation console and the trust form, for the same reason and with the same
		// consequence if they were left out: PERM001 walks this document, so an operation that is
		// not in it is an operation whose access declaration nothing checks. Leaving these off was
		// caught by the generated permissions page reporting `plugin.moderate` as declared by
		// "nothing yet" while a route declaring it was registered and serving.
		Moderation: unavailableModeration{},
		Trust:      unavailableTrust{},
	})

	return api.OpenAPI()
}

// SpecJSON renders Spec as the bytes of openapi/openapi.json.
//
// Indented and newline-terminated because it is a checked-in file a human reads in a diff, and
// deterministic because gate GEN001 regenerates it and fails on any difference: Huma marshals the
// document through maps, which encoding/json emits in sorted key order.
func SpecJSON() ([]byte, error) {
	raw, err := json.MarshalIndent(Spec(), "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal the openapi document: %w", err)
	}
	return append(raw, '\n'), nil
}

// errSpecOnly is returned by the stubs. Reaching it means a spec-only API was asked to serve
// traffic, which is a wiring bug rather than a runtime condition.
var errSpecOnly = errors.New("this api instance exists to generate the openapi document and serves nothing")

type unavailable struct{}

func (unavailable) Listings(context.Context) ([]registry.Plugin, error) {
	return nil, errSpecOnly
}

func (unavailable) Listing(context.Context, core.PluginID) (registry.Plugin, error) {
	return registry.Plugin{}, errSpecOnly
}

func (unavailable) Browse(context.Context, string) (Browsed, error) {
	return Browsed{}, errSpecOnly
}

func (unavailable) Ready(context.Context) error { return errSpecOnly }

func (unavailable) Begin(context.Context, identity.Kind, string) (auth.Begun, error) {
	return auth.Begun{}, errSpecOnly
}

func (unavailable) Complete(context.Context, identity.Kind, string, string, string) (
	auth.Completed, error,
) {
	return auth.Completed{}, errSpecOnly
}

func (unavailable) Create(context.Context, string) (auth.NewSession, error) {
	return auth.NewSession{}, errSpecOnly
}

func (unavailable) Revoke(context.Context, auth.Principal) error { return errSpecOnly }

func (unavailable) CSRFToken(auth.Principal) string { return "" }

func (unavailable) CheckCSRF(auth.Principal, string) bool { return false }

// unavailableTokens and unavailableOwnership are separate types rather than more methods on
// `unavailable` because a session and a token are both revoked, with different arguments. One
// stub cannot have two `Revoke`s, and collapsing the two domain methods onto one signature to
// make a test double simpler would be the tail wagging the dog.
type unavailableTokens struct{}

func (unavailableTokens) Mint(context.Context, auth.MintRequest) (auth.NewToken, error) {
	return auth.NewToken{}, errSpecOnly
}

func (unavailableTokens) List(context.Context, string) ([]auth.Listing, error) {
	return nil, errSpecOnly
}

func (unavailableTokens) Revoke(context.Context, string, string) error { return errSpecOnly }

// unavailablePublisher stands in for the publish path when the document is generated. The
// document describes what this BUILD exposes, not what one deployment happens to have wired.
type unavailablePublisher struct{}

func (unavailablePublisher) Publish(context.Context, release.Request) (release.Outcome, error) {
	return release.Outcome{}, errSpecOnly
}

// unavailableQueue stands in for the review queue when the document is generated.
type unavailableQueue struct{}

func (unavailableQueue) List(context.Context) ([]review.Waiting, error) { return nil, errSpecOnly }

func (unavailableQueue) Detail(context.Context, string) (review.Detail, error) {
	return review.Detail{}, errSpecOnly
}

func (unavailableQueue) Approve(context.Context, string, string, string) (review.Decision, error) {
	return review.Decision{}, errSpecOnly
}

func (unavailableQueue) Reject(context.Context, string, string, string) (review.Decision, error) {
	return review.Decision{}, errSpecOnly
}

func (unavailableQueue) Reverify(context.Context, string, string) (review.Verification, error) {
	return review.Verification{}, errSpecOnly
}

// unavailableReviewers stands in for the reviewer check when the document is generated. It answers
// FALSE rather than an error: the spec generator never serves a request, and "nobody may review"
// is the safe answer for a thing that is never asked.
type unavailableReviewers struct{}

func (unavailableReviewers) IsReviewer(context.Context, string) (bool, error) { return false, nil }

// Configured answers TRUE, which is the opposite direction from IsReviewer and is deliberate: the
// spec generator is not a deployment, and a document build must not render the "this registry has
// no reviewers" warning as though it had inspected one.
func (unavailableReviewers) Configured() bool { return true }

// unavailableModeration stands in for the moderation console when the document is generated.
type unavailableModeration struct{}

func (unavailableModeration) List(context.Context) ([]review.Listing, error) {
	return nil, errSpecOnly
}

func (unavailableModeration) Get(context.Context, string) (review.Listing, error) {
	return review.Listing{}, errSpecOnly
}

func (unavailableModeration) Delist(context.Context, string, string, string) error {
	return errSpecOnly
}

func (unavailableModeration) Relist(context.Context, string, string, string) error {
	return errSpecOnly
}

type unavailableTrust struct{}

func (unavailableTrust) SetTrust(context.Context, string, release.Trust, string, string) error {
	return errSpecOnly
}

type unavailableOwnership struct{}

func (unavailableOwnership) Mine(context.Context, string) ([]ownership.Plugin, error) {
	return nil, errSpecOnly
}

func (unavailableOwnership) Owners(context.Context, string, string) ([]ownership.Owner, error) {
	return nil, errSpecOnly
}

func (unavailableOwnership) RoleOf(context.Context, string, string) (ownership.Role, bool, error) {
	return "", false, errSpecOnly
}

func (unavailableOwnership) Add(context.Context, string, string, string, ownership.Role) error {
	return errSpecOnly
}

func (unavailableOwnership) Remove(context.Context, string, string, string) error {
	return errSpecOnly
}

func (unavailableOwnership) ClaimID(context.Context, ownership.Claim, string) error {
	return errSpecOnly
}
