// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package sqlitegen

import (
	"context"
)

const getAccount = `-- name: GetAccount :one
SELECT id, display_name, created_at, disabled_at FROM account WHERE id = ?
`

type GetAccountRow struct {
	ID          string
	DisplayName string
	CreatedAt   int64
	DisabledAt  *int64
}

func (q *Queries) GetAccount(ctx context.Context, id string) (GetAccountRow, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getAccountByIdentity = `-- name: GetAccountByIdentity :one

SELECT
    a.id,
    a.display_name,
    a.created_at,
    a.disabled_at,
    i.id AS identity_id,
    i.handle
FROM identity i
JOIN account a ON a.id = i.account_id
WHERE i.provider_kind = ? AND i.subject = ?
`

type GetAccountByIdentityParams struct {
	ProviderKind string
	Subject      string
}

type GetAccountByIdentityRow struct {
	ID          string
	DisplayName string
	CreatedAt   int64
	DisabledAt  *int64
	IdentityID  string
	Handle      string
}

// Accounts and the provider identities that prove you are one (ADR-0003).
//
// Every lookup here is by (provider_kind, subject) and NEVER by handle. The handle is decoration
// refreshed at each login; matching on it is the property the account/identity split exists to
// remove, because a GitHub rename would otherwise be indistinguishable from a different person.
// The login path's only read. It returns the account behind a (provider, subject) pair, plus the
// identity row so the caller can refresh the cached handle without a second query.
func (q *Queries) GetAccountByIdentity(ctx context.Context, arg GetAccountByIdentityParams) (GetAccountByIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByIdentity, arg.ProviderKind, arg.Subject)
	var i GetAccountByIdentityRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.IdentityID,
		&i.Handle,
	)
	return i, err
}

const getIdentityForAccount = `-- name: GetIdentityForAccount :one
SELECT provider_kind, subject, handle
FROM identity
WHERE account_id = ?
ORDER BY linked_at, id
LIMIT 1
`

type GetIdentityForAccountRow struct {
	ProviderKind string
	Subject      string
	Handle       string
}

// The identity to show a human on the account page. Ordered by linked_at so that an account with
// several identities has a stable answer rather than whichever row the planner reached first.
func (q *Queries) GetIdentityForAccount(ctx context.Context, accountID string) (GetIdentityForAccountRow, error) {
	row := q.db.QueryRowContext(ctx, getIdentityForAccount, accountID)
	var i GetIdentityForAccountRow
	err := row.Scan(&i.ProviderKind, &i.Subject, &i.Handle)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO account (id, display_name, created_at, updated_at) VALUES (?, ?, ?, ?)
`

type InsertAccountParams struct {
	ID          string
	DisplayName string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertAccount,
		arg.ID,
		arg.DisplayName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertIdentity = `-- name: InsertIdentity :exec
INSERT INTO identity (id, account_id, provider_kind, subject, handle, linked_at, refreshed_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertIdentityParams struct {
	ID           string
	AccountID    string
	ProviderKind string
	Subject      string
	Handle       string
	LinkedAt     int64
	RefreshedAt  int64
}

func (q *Queries) InsertIdentity(ctx context.Context, arg InsertIdentityParams) error {
	_, err := q.db.ExecContext(ctx, insertIdentity,
		arg.ID,
		arg.AccountID,
		arg.ProviderKind,
		arg.Subject,
		arg.Handle,
		arg.LinkedAt,
		arg.RefreshedAt,
	)
	return err
}

const refreshIdentity = `-- name: RefreshIdentity :exec
UPDATE identity SET handle = ?, refreshed_at = ? WHERE id = ?
`

type RefreshIdentityParams struct {
	Handle      string
	RefreshedAt int64
	ID          string
}

// The handle as it was at this login, and when we last looked. Never a matching key.
func (q *Queries) RefreshIdentity(ctx context.Context, arg RefreshIdentityParams) error {
	_, err := q.db.ExecContext(ctx, refreshIdentity, arg.Handle, arg.RefreshedAt, arg.ID)
	return err
}

const updateAccountDisplayName = `-- name: UpdateAccountDisplayName :exec
UPDATE account SET display_name = ?, updated_at = ? WHERE id = ?
`

type UpdateAccountDisplayNameParams struct {
	DisplayName string
	UpdatedAt   int64
	ID          string
}

func (q *Queries) UpdateAccountDisplayName(ctx context.Context, arg UpdateAccountDisplayNameParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountDisplayName, arg.DisplayName, arg.UpdatedAt, arg.ID)
	return err
}
