// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitegen

type Account struct {
	ID          string
	DisplayName string
	CreatedAt   int64
	UpdatedAt   int64
	DisabledAt  *int64
}

type AccountTrust struct {
	AccountID string
	Level     string
	SetAt     int64
	SetBy     *string
	Note      *string
}

type AuditLog struct {
	ID             string
	RecordedAt     int64
	ActorKind      string
	ActorAccountID *string
	Action         string
	SubjectKind    string
	SubjectID      *string
	Detail         *string
}

type Identity struct {
	ID           string
	AccountID    string
	ProviderKind string
	Subject      string
	Handle       string
	LinkedAt     int64
	RefreshedAt  int64
}

type IdentityProvider struct {
	Kind        string
	DisplayName string
	CanPublish  int64
	CreatedAt   int64
}

type Plugin struct {
	ID             string
	Name           string
	Description    string
	Author         string
	Homepage       string
	ClaimedAt      int64
	UpdatedAt      int64
	DelistedAt     *int64
	DelistedReason *string
}

type PluginOwner struct {
	PluginID  string
	AccountID string
	Role      string
	GrantedAt int64
	GrantedBy *string
}

type Release struct {
	ID                string
	PluginID          string
	Version           string
	State             string
	Source            string
	ArtifactUrl       string
	ArtifactSha256    *string
	ArtifactBytes     *int64
	SdkSpecifier      string
	MinimumAppVersion *string
	SubmittedBy       *string
	SubmittedAt       int64
	VerifiedAt        *int64
	ReviewedBy        *string
	ReviewedAt        *int64
	ReviewNote        *string
}
