// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ownership.sql

package sqlitegen

import (
	"context"
)

const countOwnersForPlugin = `-- name: CountOwnersForPlugin :one
SELECT count(*) FROM plugin_owner WHERE plugin_id = ?
`

func (q *Queries) CountOwnersForPlugin(ctx context.Context, pluginID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOwnersForPlugin, pluginID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePluginOwner = `-- name: DeletePluginOwner :execrows
DELETE FROM plugin_owner WHERE plugin_id = ? AND account_id = ?
`

type DeletePluginOwnerParams struct {
	PluginID  string
	AccountID string
}

// Deleting a plugin_owner row is allowed, and is the only delete in this schema that is: it removes
// a grant, not a claim. The plugin row IS the claim and a BEFORE DELETE trigger aborts any attempt
// to remove one, so an id cannot be recycled by removing its last owner.
//
// :execrows because zero rows is how "not an owner" is reported, and because the caller writes an
// audit row only when something actually changed.
func (q *Queries) DeletePluginOwner(ctx context.Context, arg DeletePluginOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePluginOwner, arg.PluginID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAccountByHandle = `-- name: GetAccountByHandle :one
SELECT a.id, a.display_name, a.disabled_at, i.handle
FROM identity i
JOIN account a ON a.id = i.account_id
WHERE i.provider_kind = ? AND lower(i.handle) = lower(?2)
ORDER BY i.linked_at, i.id
LIMIT 1
`

type GetAccountByHandleParams struct {
	ProviderKind string
	Handle       string
}

type GetAccountByHandleRow struct {
	ID          string
	DisplayName string
	DisabledAt  *int64
	Handle      string
}

// Resolving a GitHub handle to the account behind it, for the "add an owner" form.
//
// This is the ONE place a handle is matched on, and it is matched case-insensitively because that
// is how GitHub compares them and how the static registry's owners.json did. It resolves to an
// account that has ALREADY SIGNED IN: there is no way to grant ownership to somebody who has never
// authenticated here, which is deliberate -- a grant to a handle nobody has proved they hold is a
// grant to whoever registers it next.
func (q *Queries) GetAccountByHandle(ctx context.Context, arg GetAccountByHandleParams) (GetAccountByHandleRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByHandle, arg.ProviderKind, arg.Handle)
	var i GetAccountByHandleRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.DisabledAt,
		&i.Handle,
	)
	return i, err
}

const getPluginOwner = `-- name: GetPluginOwner :one
SELECT plugin_id, account_id, role, granted_at FROM plugin_owner
WHERE plugin_id = ? AND account_id = ?
`

type GetPluginOwnerParams struct {
	PluginID  string
	AccountID string
}

type GetPluginOwnerRow struct {
	PluginID  string
	AccountID string
	Role      string
	GrantedAt int64
}

func (q *Queries) GetPluginOwner(ctx context.Context, arg GetPluginOwnerParams) (GetPluginOwnerRow, error) {
	row := q.db.QueryRowContext(ctx, getPluginOwner, arg.PluginID, arg.AccountID)
	var i GetPluginOwnerRow
	err := row.Scan(
		&i.PluginID,
		&i.AccountID,
		&i.Role,
		&i.GrantedAt,
	)
	return i, err
}

const insertPluginOwner = `-- name: InsertPluginOwner :exec
INSERT INTO plugin_owner (plugin_id, account_id, role, granted_at, granted_by)
VALUES (?, ?, ?, ?, ?)
`

type InsertPluginOwnerParams struct {
	PluginID  string
	AccountID string
	Role      string
	GrantedAt int64
	GrantedBy *string
}

func (q *Queries) InsertPluginOwner(ctx context.Context, arg InsertPluginOwnerParams) error {
	_, err := q.db.ExecContext(ctx, insertPluginOwner,
		arg.PluginID,
		arg.AccountID,
		arg.Role,
		arg.GrantedAt,
		arg.GrantedBy,
	)
	return err
}

const listOwnersForPlugin = `-- name: ListOwnersForPlugin :many
SELECT
    o.account_id,
    o.role,
    o.granted_at,
    a.display_name,
    CAST(coalesce((SELECT i.handle FROM identity i WHERE i.account_id = a.id ORDER BY i.linked_at, i.id LIMIT 1), '') AS TEXT) AS handle
FROM plugin_owner o
JOIN account a ON a.id = o.account_id
WHERE o.plugin_id = ?
ORDER BY o.granted_at, o.account_id
`

type ListOwnersForPluginRow struct {
	AccountID   string
	Role        string
	GrantedAt   int64
	DisplayName string
	Handle      string
}

// The settings page. It joins the identity so a human sees a GitHub handle rather than a ULID --
// the handle is decoration, refreshed at each login, and never what anything matches on.
func (q *Queries) ListOwnersForPlugin(ctx context.Context, pluginID string) ([]ListOwnersForPluginRow, error) {
	rows, err := q.db.QueryContext(ctx, listOwnersForPlugin, pluginID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnersForPluginRow{}
	for rows.Next() {
		var i ListOwnersForPluginRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Role,
			&i.GrantedAt,
			&i.DisplayName,
			&i.Handle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginsForAccount = `-- name: ListPluginsForAccount :many

SELECT
    p.id,
    p.name,
    p.delisted_at,
    o.role,
    o.granted_at,
    (SELECT count(*) FROM "release" r WHERE r.plugin_id = p.id AND r.state = 'approved') AS approved_releases
FROM plugin_owner o
JOIN plugin p ON p.id = o.plugin_id
WHERE o.account_id = ?
ORDER BY p.id
`

type ListPluginsForAccountRow struct {
	ID               string
	Name             string
	DelistedAt       *int64
	Role             string
	GrantedAt        int64
	ApprovedReleases int64
}

// Who may change a plugin's listing (ADR-0005).
//
// Ownership is checked PER REQUEST rather than cascade-revoked, so removing an owner takes effect
// on their next call rather than after a sweep. That is why these are reads on the hot path and
// not a cached set.
//
// ASCII only: gate QRY001. sqlc slices queries out of this file by byte offset.
// The account page's "your plugins". A delisted plugin is still listed here on purpose: the id is
// still claimed, the owner still owns it, and a page that hid it would be a page that told
// somebody their plugin was gone.
func (q *Queries) ListPluginsForAccount(ctx context.Context, accountID string) ([]ListPluginsForAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listPluginsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPluginsForAccountRow{}
	for rows.Next() {
		var i ListPluginsForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DelistedAt,
			&i.Role,
			&i.GrantedAt,
			&i.ApprovedReleases,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
