// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pat.sql

package sqlitegen

import (
	"context"
)

const getPATByTokenHash = `-- name: GetPATByTokenHash :one
SELECT
    p.id,
    p.account_id,
    p.prefix,
    p.plugin_id,
    p.created_at,
    p.expires_at,
    p.last_used_at,
    p.revoked_at,
    a.display_name,
    a.disabled_at
FROM pat p
JOIN account a ON a.id = p.account_id
WHERE p.token_hash = ?
`

type GetPATByTokenHashRow struct {
	ID          string
	AccountID   string
	Prefix      string
	PluginID    *string
	CreatedAt   int64
	ExpiresAt   *int64
	LastUsedAt  *int64
	RevokedAt   *int64
	DisplayName string
	DisabledAt  *int64
}

// The read on every publish. It joins the account so a disabled account's tokens stop working in
// the same round trip: a token that outlives the account it belongs to is a credential nobody can
// revoke by disabling the account.
func (q *Queries) GetPATByTokenHash(ctx context.Context, tokenHash string) (GetPATByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getPATByTokenHash, tokenHash)
	var i GetPATByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Prefix,
		&i.PluginID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.DisplayName,
		&i.DisabledAt,
	)
	return i, err
}

const insertPAT = `-- name: InsertPAT :exec

INSERT INTO pat (id, account_id, prefix, token_hash, name, plugin_id, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPATParams struct {
	ID        string
	AccountID string
	Prefix    string
	TokenHash string
	Name      string
	PluginID  *string
	CreatedAt int64
	ExpiresAt *int64
}

// Personal access tokens: a deployment credential for one plugin's pipeline (ADR-0005).
//
// Nothing here selects by id for the purpose of AUTHENTICATING. The lookup is by token_hash, which
// is HMAC-SHA256(pepper, secret); the id and the 8-character prefix identify a row to a human, and
// neither is a credential. The secret itself is not in this database at all.
//
// ASCII only, like every file here: sqlc slices queries out of the file by byte offset and one
// multi-byte character silently scrambles the SQL it generates. Gate QRY001.
func (q *Queries) InsertPAT(ctx context.Context, arg InsertPATParams) error {
	_, err := q.db.ExecContext(ctx, insertPAT,
		arg.ID,
		arg.AccountID,
		arg.Prefix,
		arg.TokenHash,
		arg.Name,
		arg.PluginID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertPATScope = `-- name: InsertPATScope :exec
INSERT INTO pat_scope (pat_id, scope) VALUES (?, ?)
`

type InsertPATScopeParams struct {
	PatID string
	Scope string
}

func (q *Queries) InsertPATScope(ctx context.Context, arg InsertPATScopeParams) error {
	_, err := q.db.ExecContext(ctx, insertPATScope, arg.PatID, arg.Scope)
	return err
}

const listPATScopes = `-- name: ListPATScopes :many
SELECT scope FROM pat_scope WHERE pat_id = ? ORDER BY scope
`

func (q *Queries) ListPATScopes(ctx context.Context, patID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPATScopes, patID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var scope string
		if err := rows.Scan(&scope); err != nil {
			return nil, err
		}
		items = append(items, scope)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPATsForAccount = `-- name: ListPATsForAccount :many
SELECT id, prefix, name, plugin_id, created_at, expires_at, last_used_at, revoked_at
FROM pat
WHERE account_id = ?
ORDER BY created_at DESC
`

type ListPATsForAccountRow struct {
	ID         string
	Prefix     string
	Name       string
	PluginID   *string
	CreatedAt  int64
	ExpiresAt  *int64
	LastUsedAt *int64
	RevokedAt  *int64
}

// What the account page shows. No hash and no secret: there is nothing here that could
// authenticate anything.
func (q *Queries) ListPATsForAccount(ctx context.Context, accountID string) ([]ListPATsForAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listPATsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPATsForAccountRow{}
	for rows.Next() {
		var i ListPATsForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.Prefix,
			&i.Name,
			&i.PluginID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePAT = `-- name: RevokePAT :execrows
UPDATE pat SET revoked_at = ?
WHERE id = ? AND account_id = ? AND revoked_at IS NULL
`

type RevokePATParams struct {
	RevokedAt *int64
	ID        string
	AccountID string
}

// Scoped to the account on purpose: the id comes from a URL, and without this clause an owner
// could revoke somebody else's token by guessing a ULID.
//
// :execrows because the caller writes an audit row only when this changed something, and because
// zero rows is how "not yours, or already revoked" is reported without a second query that would
// tell the caller which.
func (q *Queries) RevokePAT(ctx context.Context, arg RevokePATParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokePAT, arg.RevokedAt, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchPAT = `-- name: TouchPAT :exec
UPDATE pat SET last_used_at = ? WHERE id = ?
`

type TouchPATParams struct {
	LastUsedAt *int64
	ID         string
}

// Refreshed lazily, like a session's. A write in front of every publish would put token
// bookkeeping in the single writer's queue ahead of the publish itself.
func (q *Queries) TouchPAT(ctx context.Context, arg TouchPATParams) error {
	_, err := q.db.ExecContext(ctx, touchPAT, arg.LastUsedAt, arg.ID)
	return err
}
