// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plugin.sql

package sqlitegen

import (
	"context"
)

const countCatalogue = `-- name: CountCatalogue :one
SELECT
    (SELECT count(*)
     FROM plugin p
     JOIN "release" r ON r.plugin_id = p.id AND r.state = 'approved'
     WHERE p.delisted_at IS NULL) AS listed,
    (SELECT count(*)
     FROM plugin p
     WHERE p.delisted_at IS NULL
       AND NOT EXISTS (
           SELECT 1 FROM "release" r WHERE r.plugin_id = p.id AND r.state = 'approved'
       )) AS awaiting,
    (SELECT count(*) FROM plugin WHERE delisted_at IS NOT NULL) AS delisted
`

type CountCatalogueRow struct {
	Listed   int64
	Awaiting int64
	Delisted int64
}

// What the directory shows, and what it does not.
//
// A listing that vanishes without explanation is indistinguishable from a bug, so the page counts
// the rows it drops rather than quietly serving a shorter list: `listed` is what a visitor sees,
// `awaiting` is claimed ids with nothing approved behind them yet, and `delisted` is ids that are
// kept forever and never recycled. One statement rather than three round trips, and no ids in it:
// a count is not an enumeration.
func (q *Queries) CountCatalogue(ctx context.Context) (CountCatalogueRow, error) {
	row := q.db.QueryRowContext(ctx, countCatalogue)
	var i CountCatalogueRow
	err := row.Scan(&i.Listed, &i.Awaiting, &i.Delisted)
	return i, err
}

const countCatalogueImports = `-- name: CountCatalogueImports :one
SELECT count(*) FROM audit_log
WHERE subject_kind = 'catalogue' AND action = 'catalogue.import'
`

// Whether a seed has ever been imported into this database. The audit row written by the import is
// the marker: it is durable, it is append-only, and it does not depend on inferring "we have never
// imported" from a row count somebody could one day make deletable. Uses the
// (subject_kind, subject_id) index.
func (q *Queries) CountCatalogueImports(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCatalogueImports)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlugins = `-- name: CountPlugins :one

SELECT count(*) FROM plugin
`

// Queries over the catalogue: the plugin rows, their single approved release, and the two writes
// the boot-time seed import needs.
//
// "release" is quoted throughout because RELEASE is a SQLite keyword (RELEASE SAVEPOINT). SQLite
// accepts it bare in most positions; a position where it does not would fail at boot rather than
// here, which is the wrong place to find out.
// Whether this database has a catalogue at all. The boot-time seed import reads exactly this, and
// a non-zero answer means the import must not run: an existing catalogue is never overwritten by a
// file on disk.
func (q *Queries) CountPlugins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlugins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const delistPlugin = `-- name: DelistPlugin :execrows
UPDATE plugin
SET delisted_at = ?, delisted_reason = ?, updated_at = ?
WHERE id = ? AND delisted_at IS NULL
`

type DelistPluginParams struct {
	DelistedAt     *int64
	DelistedReason *string
	UpdatedAt      int64
	ID             string
}

// Remove a plugin's listing and KEEP ITS CLAIM.
//
// An UPDATE, never a DELETE. The plugin row IS the claim (a BEFORE DELETE trigger aborts a
// removal), so delisting sets delisted_at and the id stays spoken for -- permanently, and for
// nobody else. An id whose plugin is gone must never become available to somebody else, because
// that is how you ship an update to another author's users.
//
// delisted_reason is NOT NULL here because the table's CHECK requires the pair to agree: a
// delisting with no stated reason is one nobody can review later, and a listing that vanishes
// without explanation is indistinguishable from a bug.
//
// The WHERE names the expected current state, like every state change in review.sql and for the
// same reason: zero rows is how "it was already delisted" is reported, without a Go check above
// the statement leaving a window between the read and the write.
func (q *Queries) DelistPlugin(ctx context.Context, arg DelistPluginParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, delistPlugin,
		arg.DelistedAt,
		arg.DelistedReason,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getListing = `-- name: GetListing :one
SELECT
    p.id,
    p.name,
    p.description,
    p.author,
    p.homepage,
    r.version,
    r.artifact_url,
    r.artifact_sha256,
    r.sdk_specifier,
    r.minimum_app_version,
    r.notes
FROM plugin p
JOIN "release" r ON r.plugin_id = p.id AND r.state = 'approved'
WHERE p.delisted_at IS NULL AND p.id = ?
`

type GetListingRow struct {
	ID                string
	Name              string
	Description       string
	Author            string
	Homepage          string
	Version           string
	ArtifactUrl       string
	ArtifactSha256    *string
	SdkSpecifier      string
	MinimumAppVersion *string
	Notes             *string
}

func (q *Queries) GetListing(ctx context.Context, id string) (GetListingRow, error) {
	row := q.db.QueryRowContext(ctx, getListing, id)
	var i GetListingRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Author,
		&i.Homepage,
		&i.Version,
		&i.ArtifactUrl,
		&i.ArtifactSha256,
		&i.SdkSpecifier,
		&i.MinimumAppVersion,
		&i.Notes,
	)
	return i, err
}

const getPlugin = `-- name: GetPlugin :one
SELECT id, name, delisted_at FROM plugin WHERE id = ?
`

type GetPluginRow struct {
	ID         string
	Name       string
	DelistedAt *int64
}

// Whether an id is claimed at all, and its listing state. Used by the ownership import, which must
// NOT create a plugin row for an id owners.json names but this registry does not carry: a claim on
// an id nobody can check is exactly the squatting the first-come rule exists to prevent.
func (q *Queries) GetPlugin(ctx context.Context, id string) (GetPluginRow, error) {
	row := q.db.QueryRowContext(ctx, getPlugin, id)
	var i GetPluginRow
	err := row.Scan(&i.ID, &i.Name, &i.DelistedAt)
	return i, err
}

const getPluginForModeration = `-- name: GetPluginForModeration :one
SELECT
    p.id,
    p.name,
    p.description,
    p.author,
    p.homepage,
    p.claimed_at,
    p.delisted_at,
    p.delisted_reason,
    CAST(coalesce((SELECT r.version FROM "release" r
        WHERE r.plugin_id = p.id AND r.state = 'approved' LIMIT 1), '') AS TEXT) AS live_version,
    (SELECT count(*) FROM "release" r
        WHERE r.plugin_id = p.id AND r.state = 'pending') AS pending_releases,
    (SELECT count(*) FROM plugin_owner o WHERE o.plugin_id = p.id) AS owner_count
FROM plugin p
WHERE p.id = ?
`

type GetPluginForModerationRow struct {
	ID              string
	Name            string
	Description     string
	Author          string
	Homepage        string
	ClaimedAt       int64
	DelistedAt      *int64
	DelistedReason  *string
	LiveVersion     string
	PendingReleases int64
	OwnerCount      int64
}

// One plugin for the reviewer's page. Same columns as the list, so the two surfaces cannot
// disagree about what state a plugin is in.
func (q *Queries) GetPluginForModeration(ctx context.Context, id string) (GetPluginForModerationRow, error) {
	row := q.db.QueryRowContext(ctx, getPluginForModeration, id)
	var i GetPluginForModerationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Author,
		&i.Homepage,
		&i.ClaimedAt,
		&i.DelistedAt,
		&i.DelistedReason,
		&i.LiveVersion,
		&i.PendingReleases,
		&i.OwnerCount,
	)
	return i, err
}

const insertPlugin = `-- name: InsertPlugin :exec
INSERT INTO plugin (id, name, description, author, homepage, claimed_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertPluginParams struct {
	ID          string
	Name        string
	Description string
	Author      string
	Homepage    string
	ClaimedAt   int64
	UpdatedAt   int64
}

func (q *Queries) InsertPlugin(ctx context.Context, arg InsertPluginParams) error {
	_, err := q.db.ExecContext(ctx, insertPlugin,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Author,
		arg.Homepage,
		arg.ClaimedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertRelease = `-- name: InsertRelease :exec
INSERT INTO "release" (
    id, plugin_id, version, state, source,
    artifact_url, artifact_sha256, artifact_bytes,
    sdk_specifier, minimum_app_version, notes,
    submitted_by, submitted_at, verified_at,
    reviewed_by, reviewed_at, review_note
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertReleaseParams struct {
	ID                string
	PluginID          string
	Version           string
	State             string
	Source            string
	ArtifactUrl       string
	ArtifactSha256    *string
	ArtifactBytes     *int64
	SdkSpecifier      string
	MinimumAppVersion *string
	Notes             *string
	SubmittedBy       *string
	SubmittedAt       int64
	VerifiedAt        *int64
	ReviewedBy        *string
	ReviewedAt        *int64
	ReviewNote        *string
}

// The seed importer's insert. It carries notes because the seed document is the index document:
// a catalogue captured with curl and replayed into an empty database must come back the same, and
// an import that silently dropped an author's patch notes would make the two disagree with nothing
// anywhere saying so.
func (q *Queries) InsertRelease(ctx context.Context, arg InsertReleaseParams) error {
	_, err := q.db.ExecContext(ctx, insertRelease,
		arg.ID,
		arg.PluginID,
		arg.Version,
		arg.State,
		arg.Source,
		arg.ArtifactUrl,
		arg.ArtifactSha256,
		arg.ArtifactBytes,
		arg.SdkSpecifier,
		arg.MinimumAppVersion,
		arg.Notes,
		arg.SubmittedBy,
		arg.SubmittedAt,
		arg.VerifiedAt,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.ReviewNote,
	)
	return err
}

const listListings = `-- name: ListListings :many
SELECT
    p.id,
    p.name,
    p.description,
    p.author,
    p.homepage,
    r.version,
    r.artifact_url,
    r.artifact_sha256,
    r.sdk_specifier,
    r.minimum_app_version,
    r.notes
FROM plugin p
JOIN "release" r ON r.plugin_id = p.id AND r.state = 'approved'
WHERE p.delisted_at IS NULL
ORDER BY p.id
`

type ListListingsRow struct {
	ID                string
	Name              string
	Description       string
	Author            string
	Homepage          string
	Version           string
	ArtifactUrl       string
	ArtifactSha256    *string
	SdkSpecifier      string
	MinimumAppVersion *string
	Notes             *string
}

func (q *Queries) ListListings(ctx context.Context) ([]ListListingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listListings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListingsRow{}
	for rows.Next() {
		var i ListListingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Author,
			&i.Homepage,
			&i.Version,
			&i.ArtifactUrl,
			&i.ArtifactSha256,
			&i.SdkSpecifier,
			&i.MinimumAppVersion,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnersWithTrust = `-- name: ListOwnersWithTrust :many
SELECT
    o.plugin_id,
    o.account_id,
    o.role,
    a.display_name,
    CAST(coalesce((SELECT i.handle FROM identity i WHERE i.account_id = a.id
        ORDER BY i.linked_at, i.id LIMIT 1), '') AS TEXT) AS handle,
    CAST(coalesce(t.level, '') AS TEXT) AS trust_level
FROM plugin_owner o
JOIN account a ON a.id = o.account_id
LEFT JOIN account_trust t ON t.account_id = o.account_id
ORDER BY o.plugin_id, o.granted_at, o.account_id
`

type ListOwnersWithTrustRow struct {
	PluginID    string
	AccountID   string
	Role        string
	DisplayName string
	Handle      string
	TrustLevel  string
}

// Every ownership grant in the registry, with the holder's handle and CURRENT trust tier.
//
// ALL of them in one statement, grouped by the caller, rather than a query per plugin: the
// reviewer's catalogue shows owners against every row, and a page that issued one read per plugin
// would be a page whose cost grows with the registry while it holds the reader's connection open.
//
// LEFT JOIN account_trust because NO ROW MEANS 'new'. An INNER JOIN would silently drop every
// owner nobody has assessed -- which is most of them, and exactly the ones a reviewer is looking
// for. The caller reads a NULL level as the floor, the same reading release.TrustOf gives it.
//
// plugin_id is selected so one pass can bucket the rows; the caller filters in Go rather than
// running this per plugin.
func (q *Queries) ListOwnersWithTrust(ctx context.Context) ([]ListOwnersWithTrustRow, error) {
	rows, err := q.db.QueryContext(ctx, listOwnersWithTrust)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnersWithTrustRow{}
	for rows.Next() {
		var i ListOwnersWithTrustRow
		if err := rows.Scan(
			&i.PluginID,
			&i.AccountID,
			&i.Role,
			&i.DisplayName,
			&i.Handle,
			&i.TrustLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginsForModeration = `-- name: ListPluginsForModeration :many
SELECT
    p.id,
    p.name,
    p.description,
    p.author,
    p.homepage,
    p.claimed_at,
    p.delisted_at,
    p.delisted_reason,
    CAST(coalesce((SELECT r.version FROM "release" r
        WHERE r.plugin_id = p.id AND r.state = 'approved' LIMIT 1), '') AS TEXT) AS live_version,
    (SELECT count(*) FROM "release" r
        WHERE r.plugin_id = p.id AND r.state = 'pending') AS pending_releases,
    (SELECT count(*) FROM plugin_owner o WHERE o.plugin_id = p.id) AS owner_count
FROM plugin p
ORDER BY p.id
`

type ListPluginsForModerationRow struct {
	ID              string
	Name            string
	Description     string
	Author          string
	Homepage        string
	ClaimedAt       int64
	DelistedAt      *int64
	DelistedReason  *string
	LiveVersion     string
	PendingReleases int64
	OwnerCount      int64
}

// Every plugin this registry knows, whatever its state, for the reviewer's catalogue view.
//
// NOT the directory's query, and the difference is the point of this one. SearchListings answers
// "what is publicly visible" and drops a delisted or unpublished id on the floor, counting it so
// the number is honest. A reviewer needs the rows themselves: the ids claimed and never published,
// and the ids somebody delisted, are exactly the ones moderation is about, and a moderation
// surface that could only see what the public sees would be blind to its own subject.
//
// No WHERE at all, deliberately. A filter here would be a row a reviewer cannot see, and there is
// no state of a plugin this page is not for.
func (q *Queries) ListPluginsForModeration(ctx context.Context) ([]ListPluginsForModerationRow, error) {
	rows, err := q.db.QueryContext(ctx, listPluginsForModeration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPluginsForModerationRow{}
	for rows.Next() {
		var i ListPluginsForModerationRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Author,
			&i.Homepage,
			&i.ClaimedAt,
			&i.DelistedAt,
			&i.DelistedReason,
			&i.LiveVersion,
			&i.PendingReleases,
			&i.OwnerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginsWithNoApprovedRelease = `-- name: ListPluginsWithNoApprovedRelease :many
SELECT p.id
FROM plugin p
WHERE p.delisted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM "release" r WHERE r.plugin_id = p.id AND r.state = 'approved'
  )
ORDER BY p.id
`

// The rows ListListings drops. A listing that vanishes without explanation is indistinguishable
// from a bug, so the catalogue counts and names them rather than letting them disappear between a
// claimed id and a rendered index.
func (q *Queries) ListPluginsWithNoApprovedRelease(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPluginsWithNoApprovedRelease)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const relistPlugin = `-- name: RelistPlugin :execrows
UPDATE plugin
SET delisted_at = NULL, delisted_reason = NULL, updated_at = ?
WHERE id = ? AND delisted_at IS NOT NULL
`

type RelistPluginParams struct {
	UpdatedAt int64
	ID        string
}

// Put a delisted plugin's listing back.
//
// The inverse of the statement above, and it exists because the alternative to it is a maintainer
// writing SQL against production. Delisting is reversible in the schema -- delisted_at is nullable
// -- and a moderation action a reviewer cannot undo through the same surface they performed it in
// is one that gets undone by hand, at 2am, with no audit row.
//
// It clears delisted_reason with it, because the CHECK requires the pair to agree, and the reason
// a listing WAS removed does not survive as a property of a listing that is back. It survives in
// audit_log, which is the copy that cannot be edited.
//
// Relisting does NOT restore anything else, because nothing else was taken away: the releases, the
// owners and the claim were never touched. What comes back is the row's presence in the index, and
// only if it still has an approved release -- a plugin delisted before it ever published relists
// to exactly where it was, awaiting review.
func (q *Queries) RelistPlugin(ctx context.Context, arg RelistPluginParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, relistPlugin, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const searchListings = `-- name: SearchListings :many
SELECT
    p.id,
    p.name,
    p.description,
    p.author,
    p.homepage,
    r.version,
    r.artifact_url,
    r.artifact_sha256,
    r.sdk_specifier,
    r.minimum_app_version,
    r.notes
FROM plugin p
JOIN "release" r ON r.plugin_id = p.id AND r.state = 'approved'
WHERE p.delisted_at IS NULL
  AND (instr(lower(p.id), ?1) > 0
       OR instr(lower(p.name), ?1) > 0
       OR instr(lower(p.description), ?1) > 0
       OR instr(lower(p.author), ?1) > 0)
ORDER BY p.id
`

type SearchListingsRow struct {
	ID                string
	Name              string
	Description       string
	Author            string
	Homepage          string
	Version           string
	ArtifactUrl       string
	ArtifactSha256    *string
	SdkSpecifier      string
	MinimumAppVersion *string
	Notes             *string
}

// The public directory's query. It is a SEPARATE statement from ListListings on purpose: the
// index's query must never grow a parameter a web page controls, because the index is the document
// a released client parses and its rows are decided by the schema, not by a querystring.
//
// Matching is instr() over lower(), not LIKE. Two reasons, and neither is style: instr's needle
// is LITERAL, so there are no wildcards to escape and a visitor typing % or _ searches for those
// characters rather than for everything; and sqlc v1.31.1's SQLite grammar does not parse LIKE's
// ESCAPE clause, so the alternative was an unescaped LIKE, which is the bug.
//
// SQLite's lower() folds ASCII ONLY. The Go side folds the query the same way, with A-Z and
// nothing else, so the two agree by construction: a query with non-ASCII letters matches
// case-sensitively, which is a stated limitation rather than a surprise. Plugin ids are ASCII by
// construction (core.PluginID), so ids are unaffected.
//
// instr(x, ”) is 1, so an empty query matches every row. That is why there is no CASE and no
// second parameter for "did they search at all": "show me everything" is the same statement as
// "match anything", and one code path cannot disagree with itself.
//
// There is NO FTS5 table here: the catalogue is tens of rows, and a virtual table plus a migration
// plus the triggers to keep it in step is a lot of machinery for a scan that costs microseconds.
// See issue #40 for the row count at which that stops being true.
func (q *Queries) SearchListings(ctx context.Context, needle string) ([]SearchListingsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchListings, needle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchListingsRow{}
	for rows.Next() {
		var i SearchListingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Author,
			&i.Homepage,
			&i.Version,
			&i.ArtifactUrl,
			&i.ArtifactSha256,
			&i.SdkSpecifier,
			&i.MinimumAppVersion,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
