// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plugin.sql

package sqlitegen

import (
	"context"
)

const countCatalogueImports = `-- name: CountCatalogueImports :one
SELECT count(*) FROM audit_log
WHERE subject_kind = 'catalogue' AND action = 'catalogue.import'
`

// Whether a seed has ever been imported into this database. The audit row written by the import is
// the marker: it is durable, it is append-only, and it does not depend on inferring "we have never
// imported" from a row count somebody could one day make deletable. Uses the
// (subject_kind, subject_id) index.
func (q *Queries) CountCatalogueImports(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCatalogueImports)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlugins = `-- name: CountPlugins :one

SELECT count(*) FROM plugin
`

// Queries over the catalogue: the plugin rows, their single approved release, and the two writes
// the boot-time seed import needs.
//
// "release" is quoted throughout because RELEASE is a SQLite keyword (RELEASE SAVEPOINT). SQLite
// accepts it bare in most positions; a position where it does not would fail at boot rather than
// here, which is the wrong place to find out.
// Whether this database has a catalogue at all. The boot-time seed import reads exactly this, and
// a non-zero answer means the import must not run: an existing catalogue is never overwritten by a
// file on disk.
func (q *Queries) CountPlugins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlugins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getListing = `-- name: GetListing :one
SELECT
    p.id,
    p.name,
    p.description,
    p.author,
    p.homepage,
    r.version,
    r.artifact_url,
    r.artifact_sha256,
    r.sdk_specifier,
    r.minimum_app_version,
    r.notes
FROM plugin p
JOIN "release" r ON r.plugin_id = p.id AND r.state = 'approved'
WHERE p.delisted_at IS NULL AND p.id = ?
`

type GetListingRow struct {
	ID                string
	Name              string
	Description       string
	Author            string
	Homepage          string
	Version           string
	ArtifactUrl       string
	ArtifactSha256    *string
	SdkSpecifier      string
	MinimumAppVersion *string
	Notes             *string
}

func (q *Queries) GetListing(ctx context.Context, id string) (GetListingRow, error) {
	row := q.db.QueryRowContext(ctx, getListing, id)
	var i GetListingRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Author,
		&i.Homepage,
		&i.Version,
		&i.ArtifactUrl,
		&i.ArtifactSha256,
		&i.SdkSpecifier,
		&i.MinimumAppVersion,
		&i.Notes,
	)
	return i, err
}

const getPlugin = `-- name: GetPlugin :one
SELECT id, name, delisted_at FROM plugin WHERE id = ?
`

type GetPluginRow struct {
	ID         string
	Name       string
	DelistedAt *int64
}

// Whether an id is claimed at all, and its listing state. Used by the ownership import, which must
// NOT create a plugin row for an id owners.json names but this registry does not carry: a claim on
// an id nobody can check is exactly the squatting the first-come rule exists to prevent.
func (q *Queries) GetPlugin(ctx context.Context, id string) (GetPluginRow, error) {
	row := q.db.QueryRowContext(ctx, getPlugin, id)
	var i GetPluginRow
	err := row.Scan(&i.ID, &i.Name, &i.DelistedAt)
	return i, err
}

const insertPlugin = `-- name: InsertPlugin :exec
INSERT INTO plugin (id, name, description, author, homepage, claimed_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertPluginParams struct {
	ID          string
	Name        string
	Description string
	Author      string
	Homepage    string
	ClaimedAt   int64
	UpdatedAt   int64
}

func (q *Queries) InsertPlugin(ctx context.Context, arg InsertPluginParams) error {
	_, err := q.db.ExecContext(ctx, insertPlugin,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Author,
		arg.Homepage,
		arg.ClaimedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertRelease = `-- name: InsertRelease :exec
INSERT INTO "release" (
    id, plugin_id, version, state, source,
    artifact_url, artifact_sha256, artifact_bytes,
    sdk_specifier, minimum_app_version, notes,
    submitted_by, submitted_at, verified_at,
    reviewed_by, reviewed_at, review_note
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertReleaseParams struct {
	ID                string
	PluginID          string
	Version           string
	State             string
	Source            string
	ArtifactUrl       string
	ArtifactSha256    *string
	ArtifactBytes     *int64
	SdkSpecifier      string
	MinimumAppVersion *string
	Notes             *string
	SubmittedBy       *string
	SubmittedAt       int64
	VerifiedAt        *int64
	ReviewedBy        *string
	ReviewedAt        *int64
	ReviewNote        *string
}

// The seed importer's insert. It carries notes because the seed document is the index document:
// a catalogue captured with curl and replayed into an empty database must come back the same, and
// an import that silently dropped an author's patch notes would make the two disagree with nothing
// anywhere saying so.
func (q *Queries) InsertRelease(ctx context.Context, arg InsertReleaseParams) error {
	_, err := q.db.ExecContext(ctx, insertRelease,
		arg.ID,
		arg.PluginID,
		arg.Version,
		arg.State,
		arg.Source,
		arg.ArtifactUrl,
		arg.ArtifactSha256,
		arg.ArtifactBytes,
		arg.SdkSpecifier,
		arg.MinimumAppVersion,
		arg.Notes,
		arg.SubmittedBy,
		arg.SubmittedAt,
		arg.VerifiedAt,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.ReviewNote,
	)
	return err
}

const listListings = `-- name: ListListings :many
SELECT
    p.id,
    p.name,
    p.description,
    p.author,
    p.homepage,
    r.version,
    r.artifact_url,
    r.artifact_sha256,
    r.sdk_specifier,
    r.minimum_app_version,
    r.notes
FROM plugin p
JOIN "release" r ON r.plugin_id = p.id AND r.state = 'approved'
WHERE p.delisted_at IS NULL
ORDER BY p.id
`

type ListListingsRow struct {
	ID                string
	Name              string
	Description       string
	Author            string
	Homepage          string
	Version           string
	ArtifactUrl       string
	ArtifactSha256    *string
	SdkSpecifier      string
	MinimumAppVersion *string
	Notes             *string
}

func (q *Queries) ListListings(ctx context.Context) ([]ListListingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listListings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListListingsRow{}
	for rows.Next() {
		var i ListListingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Author,
			&i.Homepage,
			&i.Version,
			&i.ArtifactUrl,
			&i.ArtifactSha256,
			&i.SdkSpecifier,
			&i.MinimumAppVersion,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginsWithNoApprovedRelease = `-- name: ListPluginsWithNoApprovedRelease :many
SELECT p.id
FROM plugin p
WHERE p.delisted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM "release" r WHERE r.plugin_id = p.id AND r.state = 'approved'
  )
ORDER BY p.id
`

// The rows ListListings drops. A listing that vanishes without explanation is indistinguishable
// from a bug, so the catalogue counts and names them rather than letting them disappear between a
// claimed id and a rendered index.
func (q *Queries) ListPluginsWithNoApprovedRelease(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPluginsWithNoApprovedRelease)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
