// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publish.sql

package sqlitegen

import (
	"context"
)

const canAccountPublish = `-- name: CanAccountPublish :one

SELECT count(*) FROM identity i
JOIN identity_provider p ON p.kind = i.provider_kind
WHERE i.account_id = ? AND p.can_publish = 1
`

// The publish path: the reads a release submission needs, and the two writes it makes.
//
// ASCII only: gate QRY001. sqlc slices queries out of this file by byte offset, so one em dash in
// a comment scrambles every query after it and the failure arrives at runtime.
//
// "release" is quoted throughout because RELEASE is a SQLite keyword (RELEASE SAVEPOINT).
// Whether this account holds an identity from a provider that may publish.
//
// ADR-0004 and ADR-0011: only GitHub identities may publish, and that is a CHECK against
// identity_provider.kind rather than a column an operator sets. This query reads the CHECKed
// column rather than comparing the provider kind in Go, so the answer comes from the same place
// the constraint does -- a second copy of "which providers may publish" in a Go switch is a copy
// that can disagree with the database.
func (q *Queries) CanAccountPublish(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, canAccountPublish, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAccountHandle = `-- name: GetAccountHandle :one
SELECT CAST(coalesce((
    SELECT i.handle FROM identity i
    WHERE i.account_id = a.id AND i.provider_kind = 'github'
    ORDER BY i.linked_at, i.id LIMIT 1
), '') AS TEXT) AS handle
FROM account a WHERE a.id = ?
`

// The GitHub handle behind an account id, for a reviewer who is looking at a queue full of ULIDs.
// Decoration, refreshed at each login, and never what anything matches on.
func (q *Queries) GetAccountHandle(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAccountHandle, id)
	var handle string
	err := row.Scan(&handle)
	return handle, err
}

const getAccountTrust = `-- name: GetAccountTrust :one
SELECT account_id, level, set_at, set_by, note FROM account_trust WHERE account_id = ?
`

// An account's trust tier. NO ROW MEANS 'new', which is the floor and the default: an account that
// has never been assessed is one nothing should be automated for, and inventing a row at first
// sign-in would make "never assessed" and "assessed and found ordinary" the same state.
func (q *Queries) GetAccountTrust(ctx context.Context, accountID string) (AccountTrust, error) {
	row := q.db.QueryRowContext(ctx, getAccountTrust, accountID)
	var i AccountTrust
	err := row.Scan(
		&i.AccountID,
		&i.Level,
		&i.SetAt,
		&i.SetBy,
		&i.Note,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT account_id, operation, idempotency_key, request_hash, release_id, created_at
FROM idempotency_key
WHERE account_id = ? AND operation = ? AND idempotency_key = ?
`

type GetIdempotencyKeyParams struct {
	AccountID      string
	Operation      string
	IdempotencyKey string
}

// A request this server has already answered. The request_hash comes back so the caller can tell a
// replay of the SAME request from a key reused for a different one, which is a 409 rather than a
// replay: answering with the old release's id would tell somebody their new version published
// when it did not.
func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyKey, arg.AccountID, arg.Operation, arg.IdempotencyKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.AccountID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ReleaseID,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestApprovedRelease = `-- name: GetLatestApprovedRelease :one
SELECT
    id, version, artifact_url, artifact_sha256, artifact_bytes, submitted_at, verified_at
FROM "release"
WHERE plugin_id = ? AND state = 'approved'
`

type GetLatestApprovedReleaseRow struct {
	ID             string
	Version        string
	ArtifactUrl    string
	ArtifactSha256 *string
	ArtifactBytes  *int64
	SubmittedAt    int64
	VerifiedAt     *int64
}

// The release currently on the wire for a plugin, if there is one.
//
// It is what a version bump is compared against, and the partial unique index
// release_one_approved_per_plugin is what makes "the approved release" a single row rather than
// whichever one this query reached first.
func (q *Queries) GetLatestApprovedRelease(ctx context.Context, pluginID string) (GetLatestApprovedReleaseRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestApprovedRelease, pluginID)
	var i GetLatestApprovedReleaseRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.ArtifactUrl,
		&i.ArtifactSha256,
		&i.ArtifactBytes,
		&i.SubmittedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const getReleaseByID = `-- name: GetReleaseByID :one
SELECT
    id, plugin_id, version, state, source,
    artifact_url, artifact_sha256, artifact_bytes,
    sdk_specifier, minimum_app_version,
    submitted_by, submitted_at, verified_at,
    reviewed_by, reviewed_at, review_note, notes
FROM "release"
WHERE id = ?
`

// One release row, for rebuilding the answer to a replayed idempotency key.
func (q *Queries) GetReleaseByID(ctx context.Context, id string) (Release, error) {
	row := q.db.QueryRowContext(ctx, getReleaseByID, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.Version,
		&i.State,
		&i.Source,
		&i.ArtifactUrl,
		&i.ArtifactSha256,
		&i.ArtifactBytes,
		&i.SdkSpecifier,
		&i.MinimumAppVersion,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.Notes,
	)
	return i, err
}

const getReleaseByVersion = `-- name: GetReleaseByVersion :one
SELECT id, version, state, submitted_at FROM "release"
WHERE plugin_id = ? AND version = ?
`

type GetReleaseByVersionParams struct {
	PluginID string
	Version  string
}

type GetReleaseByVersionRow struct {
	ID          string
	Version     string
	State       string
	SubmittedAt int64
}

// Whether a version has been used for this plugin before, in ANY state.
//
// A version is used once per plugin, ever -- release_plugin_version_key enforces it over a table
// nothing deletes from. Reading it first turns "UNIQUE constraint failed" into an answer that
// names the version and says which state the existing row is in.
func (q *Queries) GetReleaseByVersion(ctx context.Context, arg GetReleaseByVersionParams) (GetReleaseByVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getReleaseByVersion, arg.PluginID, arg.Version)
	var i GetReleaseByVersionRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.State,
		&i.SubmittedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO idempotency_key (account_id, operation, idempotency_key, request_hash, release_id, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertIdempotencyKeyParams struct {
	AccountID      string
	Operation      string
	IdempotencyKey string
	RequestHash    string
	ReleaseID      string
	CreatedAt      int64
}

// Written in the same transaction as the release it records. A key row without its release, or a
// release without its key row, would each make a re-run do the wrong thing exactly once.
func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertIdempotencyKey,
		arg.AccountID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ReleaseID,
		arg.CreatedAt,
	)
	return err
}

const insertPublishRelease = `-- name: InsertPublishRelease :exec
INSERT INTO "release" (
    id, plugin_id, version, state, source,
    artifact_url, artifact_sha256, artifact_bytes,
    sdk_specifier, minimum_app_version, notes,
    submitted_by, submitted_at, verified_at, review_note
) VALUES (?, ?, ?, ?, 'publish', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPublishReleaseParams struct {
	ID                string
	PluginID          string
	Version           string
	State             string
	ArtifactUrl       string
	ArtifactSha256    *string
	ArtifactBytes     *int64
	SdkSpecifier      string
	MinimumAppVersion *string
	Notes             *string
	SubmittedBy       *string
	SubmittedAt       int64
	VerifiedAt        *int64
	ReviewNote        *string
}

// The publish path's insert. Narrower than InsertRelease, which the seed importer uses: a
// published release always has a submitter, never has a reviewer yet, and always carries
// source = 'publish'. Columns a publish cannot set are absent rather than passed as NULL, so a
// caller cannot set them by accident.
//
// artifact_sha256 and verified_at are written TOGETHER or not at all. That pairing is what the
// release_a_stored_hash_was_verified_or_imported CHECK reads: a hash with no record of when this
// server computed it is a hash that came from somewhere else.
func (q *Queries) InsertPublishRelease(ctx context.Context, arg InsertPublishReleaseParams) error {
	_, err := q.db.ExecContext(ctx, insertPublishRelease,
		arg.ID,
		arg.PluginID,
		arg.Version,
		arg.State,
		arg.ArtifactUrl,
		arg.ArtifactSha256,
		arg.ArtifactBytes,
		arg.SdkSpecifier,
		arg.MinimumAppVersion,
		arg.Notes,
		arg.SubmittedBy,
		arg.SubmittedAt,
		arg.VerifiedAt,
		arg.ReviewNote,
	)
	return err
}

const setAccountTrust = `-- name: SetAccountTrust :exec
INSERT INTO account_trust (account_id, level, set_at, set_by, note)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (account_id) DO UPDATE SET
    level = excluded.level,
    set_at = excluded.set_at,
    set_by = excluded.set_by,
    note = excluded.note
`

type SetAccountTrustParams struct {
	AccountID string
	Level     string
	SetAt     int64
	SetBy     *string
	Note      *string
}

// Raise or lower an account's tier. An upsert, because a tier is a property of the account rather
// than a history: the history is in audit_log, which is append-only and cannot be edited, and that
// is the copy an incident review reads.
func (q *Queries) SetAccountTrust(ctx context.Context, arg SetAccountTrustParams) error {
	_, err := q.db.ExecContext(ctx, setAccountTrust,
		arg.AccountID,
		arg.Level,
		arg.SetAt,
		arg.SetBy,
		arg.Note,
	)
	return err
}
