// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package sqlitegen

import (
	"context"
)

const approveRelease = `-- name: ApproveRelease :execrows
UPDATE "release"
SET state = 'approved', reviewed_by = ?, reviewed_at = ?, review_note = ?
WHERE id = ? AND state = 'pending'
`

type ApproveReleaseParams struct {
	ReviewedBy *string
	ReviewedAt *int64
	ReviewNote *string
	ID         string
}

// Make a release the plugin's live one.
//
// The WHERE requires it to still be pending. Zero rows means somebody else got there first, or it
// was rejected while this reviewer was reading it, and that is reported rather than retried.
func (q *Queries) ApproveRelease(ctx context.Context, arg ApproveReleaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, approveRelease,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.ReviewNote,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countPendingReleases = `-- name: CountPendingReleases :one
SELECT count(*) FROM "release" WHERE state = 'pending'
`

// The queue depth. A number nobody looks at is a number that grows, so it is logged at boot and
// reported on the account surface rather than being discoverable only by listing.
func (q *Queries) CountPendingReleases(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingReleases)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReleaseForReview = `-- name: GetReleaseForReview :one
SELECT
    r.id,
    r.plugin_id,
    p.name AS plugin_name,
    r.version,
    r.state,
    r.source,
    r.artifact_url,
    r.artifact_sha256,
    r.artifact_bytes,
    r.sdk_specifier,
    r.minimum_app_version,
    r.notes,
    r.submitted_by,
    r.submitted_at,
    r.verified_at,
    r.reviewed_by,
    r.reviewed_at,
    r.review_note,
    CAST(coalesce(sub.display_name, '') AS TEXT) AS submitter_name,
    CAST(coalesce((SELECT i.handle FROM identity i WHERE i.account_id = r.submitted_by
        ORDER BY i.linked_at, i.id LIMIT 1), '') AS TEXT) AS submitter_handle,
    CAST(coalesce(st.level, '') AS TEXT) AS submitter_trust,
    CAST(coalesce((SELECT prior.version FROM "release" prior
        WHERE prior.plugin_id = r.plugin_id AND prior.state = 'approved' AND prior.id <> r.id
        LIMIT 1), '') AS TEXT) AS live_version
FROM "release" r
JOIN plugin p ON p.id = r.plugin_id
LEFT JOIN account sub ON sub.id = r.submitted_by
LEFT JOIN account_trust st ON st.account_id = r.submitted_by
WHERE r.id = ?
`

type GetReleaseForReviewRow struct {
	ID                string
	PluginID          string
	PluginName        string
	Version           string
	State             string
	Source            string
	ArtifactUrl       string
	ArtifactSha256    *string
	ArtifactBytes     *int64
	SdkSpecifier      string
	MinimumAppVersion *string
	Notes             *string
	SubmittedBy       *string
	SubmittedAt       int64
	VerifiedAt        *int64
	ReviewedBy        *string
	ReviewedAt        *int64
	ReviewNote        *string
	SubmitterName     string
	SubmitterHandle   string
	SubmitterTrust    string
	LiveVersion       string
}

// One release, whatever state it is in, with the plugin's name and what it would replace.
//
// NOT restricted to 'pending', deliberately. A reviewer who has just approved something is
// redirected back to the page they acted on, and a page that 404ed the moment it was decided would
// leave them unable to see what they did -- or to read the audit row that records it.
//
// live_version is what this release would replace, empty when the plugin has nothing approved.
// Excluding the row itself matters: once THIS release is the approved one, an unfiltered subquery
// would report the release as replacing itself.
//
// The submitter's name, handle and CURRENT trust tier come back with the row, so a reviewer is
// never guessing whose submission this is or what this registry already decided about them. Both
// joins are LEFT: submitted_by is nullable for an imported release, and NO account_trust ROW MEANS
// 'new' -- an INNER JOIN would drop every submission from an account nobody has assessed, which is
// most of them and exactly the ones a reviewer is looking at. An empty level is read as the floor,
// the same reading release.TrustOf gives it.
func (q *Queries) GetReleaseForReview(ctx context.Context, id string) (GetReleaseForReviewRow, error) {
	row := q.db.QueryRowContext(ctx, getReleaseForReview, id)
	var i GetReleaseForReviewRow
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.PluginName,
		&i.Version,
		&i.State,
		&i.Source,
		&i.ArtifactUrl,
		&i.ArtifactSha256,
		&i.ArtifactBytes,
		&i.SdkSpecifier,
		&i.MinimumAppVersion,
		&i.Notes,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.VerifiedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNote,
		&i.SubmitterName,
		&i.SubmitterHandle,
		&i.SubmitterTrust,
		&i.LiveVersion,
	)
	return i, err
}

const listAuditForPlugin = `-- name: ListAuditForPlugin :many
SELECT
    a.id,
    a.recorded_at,
    a.actor_kind,
    a.actor_account_id,
    a.action,
    a.detail,
    CAST(coalesce(acct.display_name, '') AS TEXT) AS actor_name
FROM audit_log a
LEFT JOIN account acct ON acct.id = a.actor_account_id
WHERE a.subject_kind = 'plugin' AND a.subject_id = ?
ORDER BY a.recorded_at, a.id
`

type ListAuditForPluginRow struct {
	ID             string
	RecordedAt     int64
	ActorKind      string
	ActorAccountID *string
	Action         string
	Detail         *string
	ActorName      string
}

// Every audit row whose subject is this PLUGIN.
//
// A publish is recorded against the plugin, not the release -- an incident review asks "what has
// happened to this plugin" -- so the row that says WHY a release is in the queue, carrying the
// quarantine reasons and the submitted hash, is not reachable by the query above. The caller keeps
// the rows whose detail names this release and drops the rest, rather than this filtering on the
// shape of a JSON document from SQL.
func (q *Queries) ListAuditForPlugin(ctx context.Context, subjectID *string) ([]ListAuditForPluginRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditForPlugin, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditForPluginRow{}
	for rows.Next() {
		var i ListAuditForPluginRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordedAt,
			&i.ActorKind,
			&i.ActorAccountID,
			&i.Action,
			&i.Detail,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditForRelease = `-- name: ListAuditForRelease :many
SELECT
    a.id,
    a.recorded_at,
    a.actor_kind,
    a.actor_account_id,
    a.action,
    a.detail,
    CAST(coalesce(acct.display_name, '') AS TEXT) AS actor_name
FROM audit_log a
LEFT JOIN account acct ON acct.id = a.actor_account_id
WHERE a.subject_kind = 'release' AND a.subject_id = ?
ORDER BY a.recorded_at, a.id
`

type ListAuditForReleaseRow struct {
	ID             string
	RecordedAt     int64
	ActorKind      string
	ActorAccountID *string
	Action         string
	Detail         *string
	ActorName      string
}

// Every audit row whose SUBJECT is this release: the approvals, rejections and re-verifications.
//
// The account is joined so a reviewer reads a name rather than a ULID. LEFT JOIN because a system
// action names no account, and an INNER JOIN would silently drop exactly the rows nobody performed.
func (q *Queries) ListAuditForRelease(ctx context.Context, subjectID *string) ([]ListAuditForReleaseRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditForRelease, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditForReleaseRow{}
	for rows.Next() {
		var i ListAuditForReleaseRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordedAt,
			&i.ActorKind,
			&i.ActorAccountID,
			&i.Action,
			&i.Detail,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHandlesForAccount = `-- name: ListHandlesForAccount :many
SELECT provider_kind, handle FROM identity WHERE account_id = ? ORDER BY linked_at, id
`

type ListHandlesForAccountRow struct {
	ProviderKind string
	Handle       string
}

// Every provider handle an account holds, for the reviewer check.
//
// All of them rather than the first: an account with two linked identities holds both, and picking
// one by linked_at would make whether somebody can review depend on the order they signed in.
func (q *Queries) ListHandlesForAccount(ctx context.Context, accountID string) ([]ListHandlesForAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listHandlesForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHandlesForAccountRow{}
	for rows.Next() {
		var i ListHandlesForAccountRow
		if err := rows.Scan(&i.ProviderKind, &i.Handle); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReleases = `-- name: ListPendingReleases :many

SELECT
    r.id,
    r.plugin_id,
    p.name AS plugin_name,
    r.version,
    r.artifact_url,
    r.artifact_sha256,
    r.artifact_bytes,
    r.submitted_by,
    r.submitted_at,
    r.verified_at,
    r.review_note,
    CAST(coalesce(sub.display_name, '') AS TEXT) AS submitter_name,
    CAST(coalesce((SELECT i.handle FROM identity i WHERE i.account_id = r.submitted_by
        ORDER BY i.linked_at, i.id LIMIT 1), '') AS TEXT) AS submitter_handle,
    CAST(coalesce(st.level, '') AS TEXT) AS submitter_trust,
    (SELECT count(*) FROM "release" prior
        WHERE prior.plugin_id = r.plugin_id AND prior.state = 'approved') AS approved_releases
FROM "release" r
JOIN plugin p ON p.id = r.plugin_id
LEFT JOIN account sub ON sub.id = r.submitted_by
LEFT JOIN account_trust st ON st.account_id = r.submitted_by
WHERE r.state = 'pending'
ORDER BY r.submitted_at, r.id
`

type ListPendingReleasesRow struct {
	ID               string
	PluginID         string
	PluginName       string
	Version          string
	ArtifactUrl      string
	ArtifactSha256   *string
	ArtifactBytes    *int64
	SubmittedBy      *string
	SubmittedAt      int64
	VerifiedAt       *int64
	ReviewNote       *string
	SubmitterName    string
	SubmitterHandle  string
	SubmitterTrust   string
	ApprovedReleases int64
}

// The review queue: reading what is waiting, and the three state changes a reviewer can make.
//
// ASCII only: gate QRY001. sqlc slices queries out of this file by byte offset.
//
// "release" is quoted throughout because RELEASE is a SQLite keyword (RELEASE SAVEPOINT).
//
// EVERY STATE CHANGE BELOW NAMES THE EXPECTED CURRENT STATE IN ITS WHERE CLAUSE, and every one is
// :execrows. That is not defensive style: it is how two reviewers acting at the same moment
// produce one change and one honest "that release is no longer pending" rather than two approvals
// racing over the same row. A Go check above the statement leaves a window; the WHERE does not.
// What is waiting for a human, oldest first.
//
// Oldest first because a queue people work from the top of is a queue where the bottom is never
// reached, and the bottom is where a submission that has been waiting a fortnight sits.
//
// It carries verified_at and artifact_sha256 so the queue can SHOW which entries were never
// verified. Those are the ones a reviewer must not simply wave through -- and the database will
// refuse to approve them anyway (release_approved_has_a_hash), so a queue that did not show it
// would be sending reviewers into an error.
//
// The submitter's name, handle and CURRENT trust tier come back with the row, so a reviewer is
// never guessing whose submission this is or what this registry already decided about them. Both
// joins are LEFT: submitted_by is nullable for an imported release, and NO account_trust ROW MEANS
// 'new' -- an INNER JOIN would drop every submission from an account nobody has assessed, which is
// most of them and exactly the ones a reviewer is looking at. An empty level is read as the floor,
// the same reading release.TrustOf gives it.
func (q *Queries) ListPendingReleases(ctx context.Context) ([]ListPendingReleasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingReleasesRow{}
	for rows.Next() {
		var i ListPendingReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.PluginName,
			&i.Version,
			&i.ArtifactUrl,
			&i.ArtifactSha256,
			&i.ArtifactBytes,
			&i.SubmittedBy,
			&i.SubmittedAt,
			&i.VerifiedAt,
			&i.ReviewNote,
			&i.SubmitterName,
			&i.SubmitterHandle,
			&i.SubmitterTrust,
			&i.ApprovedReleases,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordReleaseVerification = `-- name: RecordReleaseVerification :execrows
UPDATE "release"
SET artifact_sha256 = ?, artifact_bytes = ?, verified_at = ?, review_note = ?
WHERE id = ? AND state = 'pending' AND verified_at IS NULL
`

type RecordReleaseVerificationParams struct {
	ArtifactSha256 *string
	ArtifactBytes  *int64
	VerifiedAt     *int64
	ReviewNote     *string
	ID             string
}

// Write the hash and size THIS SERVER computed onto a release it had not managed to verify.
//
// TWO CONDITIONS, AND BOTH ARE LOAD-BEARING.
//
// verified_at IS NULL means this can only ever fill in a blank. It cannot change a hash that is
// already recorded: a stored hash is what clients verify against, and a statement that could
// rewrite one would be a way to swap the bytes behind an approved listing without anybody
// reviewing the swap -- which is the exact property this whole service exists to keep.
//
// state = 'pending' is the one that is easy to leave out, and leaving it out was a real bug. The
// artifact fetch runs OUTSIDE the transaction, because it takes up to forty-five seconds and
// SQLite has one writer. So another reviewer can reject the release while that fetch is in
// flight. With only the verified_at condition this statement still matched the now-rejected row:
// it wrote a hash onto it AND replaced review_note -- destroying the rejection reason, which is
// the only way the author ever learns why their release was refused.
func (q *Queries) RecordReleaseVerification(ctx context.Context, arg RecordReleaseVerificationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordReleaseVerification,
		arg.ArtifactSha256,
		arg.ArtifactBytes,
		arg.VerifiedAt,
		arg.ReviewNote,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rejectRelease = `-- name: RejectRelease :execrows
UPDATE "release"
SET state = 'rejected', reviewed_by = ?, reviewed_at = ?, review_note = ?
WHERE id = ? AND state = 'pending'
`

type RejectReleaseParams struct {
	ReviewedBy *string
	ReviewedAt *int64
	ReviewNote *string
	ID         string
}

// Refuse a release. The row STAYS: it is the record of what was submitted and turned down, and the
// version it used is never freed (a version is used once per plugin, ever).
func (q *Queries) RejectRelease(ctx context.Context, arg RejectReleaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rejectRelease,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.ReviewNote,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const supersedeApprovedRelease = `-- name: SupersedeApprovedRelease :execrows
UPDATE "release"
SET state = 'superseded'
WHERE plugin_id = ? AND state = 'approved'
`

// Retire whatever is currently live for a plugin, so a new approval can take its place.
//
// Run in the SAME transaction as the approval that replaces it. The partial unique index
// release_one_approved_per_plugin permits exactly one approved row per plugin, so doing this
// second, or in another transaction, is a constraint violation rather than a race -- which is the
// index doing its job, and is still a failed approval somebody has to understand.
//
// Superseding is a STATE CHANGE and never a delete: ADR-0010 keeps every release row, because they
// are the record of what was approved and by whom.
func (q *Queries) SupersedeApprovedRelease(ctx context.Context, pluginID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, supersedeApprovedRelease, pluginID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
