// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlitegen

import (
	"context"
)

const deleteExpiredOAuthFlows = `-- name: DeleteExpiredOAuthFlows :exec
= ?;

DELETE FROM oauth_flow WHERE expires_at
`

func (q *Queries) DeleteExpiredOAuthFlows(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredOAuthFlows, expiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
C;

DELETE FROM session WHERE expires_at
`

// Sessions carry no history worth keeping past their expiry — the audit log records the logins.
// Deleting is allowed here precisely because of that, which is why this table has no no-delete
// trigger and audit_log does.
func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteOAuthFlow = `-- name: DeleteOAuthFlow :exec
= ?;

DELETE FROM oauth_flow WHERE state_hash
`

// SINGLE USE. The row is deleted the moment it is redeemed, which is the property a signed cookie
// could not have given us: a replayed callback finds nothing and is refused.
func (q *Queries) DeleteOAuthFlow(ctx context.Context, stateHash string) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthFlow, stateHash)
	return err
}

const getOAuthFlow = `-- name: GetOAuthFlow :one
?);

SELECT state_hash, provider_kind, code_verifier, redirect_to, created_at, expires_at
FROM oauth_flow
WHERE state_hash
`

func (q *Queries) GetOAuthFlow(ctx context.Context, stateHash string) (OauthFlow, error) {
	row := q.db.QueryRowContext(ctx, getOAuthFlow, stateHash)
	var i OauthFlow
	err := row.Scan(
		&i.StateHash,
		&i.ProviderKind,
		&i.CodeVerifier,
		&i.RedirectTo,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
);

SELECT
    s.id,
    s.account_id,
    s.created_at,
    s.last_seen_at,
    s.expires_at,
    s.revoked_at,
    a.display_name,
    a.disabled_at
FROM session s
JOIN account a ON a.id = s.account_id
WHERE s.token_hash =
`

type GetSessionByTokenHashRow struct {
	ID          string
	AccountID   string
	CreatedAt   int64
	LastSeenAt  int64
	ExpiresAt   int64
	RevokedAt   *int64
	DisplayName string
	DisabledAt  *int64
}

// The read on every authenticated request. It joins the account so that a disabled account is
// visible in the same round trip: a session that outlives the account it belongs to would be a
// credential nobody can revoke by disabling the account.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.DisplayName,
		&i.DisabledAt,
	)
	return i, err
}

const insertOAuthFlow = `-- name: InsertOAuthFlow :exec
< ?;

INSERT INTO oauth_flow (state_hash, provider_kind, code_verifier, redirect_to, created_at, expires_at)
VALUES (?, ?, ?, ?, ?
`

type InsertOAuthFlowParams struct {
	StateHash    string
	ProviderKind string
	CodeVerifier string
	RedirectTo   string
	CreatedAt    int64
	ExpiresAt    int64
}

func (q *Queries) InsertOAuthFlow(ctx context.Context, arg InsertOAuthFlowParams) error {
	_, err := q.db.ExecContext(ctx, insertOAuthFlow,
		arg.StateHash,
		arg.ProviderKind,
		arg.CodeVerifier,
		arg.RedirectTo,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec

INSERT INTO session (id, account_id, token_hash, created_at, last_seen_at, expires_at)
VALUES (?, ?, ?, ?, ?,
`

type InsertSessionParams struct {
	ID         string
	AccountID  string
	TokenHash  string
	CreatedAt  int64
	LastSeenAt int64
	ExpiresAt  int64
}

// Browser sessions and the in-flight OAuth handshakes that create them.
//
// Nothing here selects a session by id. The lookup is always by token_hash, because the id is not
// a credential and the secret is never stored — so "find the session this cookie belongs to" is a
// keyed-hash lookup and cannot be anything else.
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
	)
	return err
}

const listSessionsForAccount = `-- name: ListSessionsForAccount :many
L;

SELECT id, created_at, last_seen_at, expires_at, revoked_at
FROM session
WHERE account_id = ?
ORDER BY created_at DE
`

type ListSessionsForAccountRow struct {
	ID         string
	CreatedAt  int64
	LastSeenAt int64
	ExpiresAt  int64
	RevokedAt  *int64
}

func (q *Queries) ListSessionsForAccount(ctx context.Context, accountID string) ([]ListSessionsForAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsForAccountRow{}
	for rows.Next() {
		var i ListSessionsForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
?;

UPDATE session SET revoked_at = ? WHERE id = ? AND revoked_at IS NU
`

type RevokeSessionParams struct {
	RevokedAt *int64
	ID        string
}

// Idempotent by the WHERE: logging out twice records the first time, not the second.
func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeSession, arg.RevokedAt, arg.ID)
	return err
}

const touchSession = `-- name: TouchSession :exec
?;

UPDATE session SET last_seen_at = ? WHERE id =
`

type TouchSessionParams struct {
	LastSeenAt int64
	ID         string
}

// Called at most once per session per touch interval, not once per request: this database has a
// single writer, and a write in front of every authenticated read would put session bookkeeping
// ahead of publishing in the write queue.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastSeenAt, arg.ID)
	return err
}
